// <auto-generated />
using DataDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113034833_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StudentSocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcademicLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AddictionScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AffectsAcademicPerformance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgDailyUsageHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictsOverSocialMedia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MentalHealthScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MostUsedPlatform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SleepHoursPerNight")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StudentSocialMedias");
                });
#pragma warning restore 612, 618
        }
    }
}
